---
.deploy-sample-next-app-k8s-dev:
  image:
    name: $CI_REGISTRY/$IMAGE_INFRA_BASE_NAME/docker-kube:latest
    entrypoint: [""]
  before_script:
    - /apps/create-kubeconfig.sh
    - HASH_BRANCH_NAME=$(printf "$CI_COMMIT_REF_NAME" | sha1sum | cut -c1-5)
    - export HASH_BRANCH_INGRESS=$HASH_BRANCH_NAME-
    - export HASH_BRANCH_NAME=-$HASH_BRANCH_NAME
    - envsubst < k8s/deployment.yml > k8s/deployment-sample-next-app.yml
    - envsubst < k8s/service.yml > k8s/service-sample-next-app.yml
    - envsubst < k8s/ingress.yml > k8s/ingress-sample-next-app.yml
  script:
    - kubectl apply -f k8s/deployment-sample-next-app.yml
    - kubectl apply -f k8s/service-sample-next-app.yml
    - kubectl apply -f k8s/ingress-sample-next-app.yml
  allow_failure: false

.deploy-sample-next-app-k8s-prod:
  image:
    name: $CI_REGISTRY/$IMAGE_INFRA_BASE_NAME/docker-kube:latest
    entrypoint: [""]
  before_script:
    - /apps/create-kubeconfig.sh
    - envsubst < k8s/deployment.yml > k8s/deployment-sample-next-app.yml
    - envsubst < k8s/service.yml > k8s/service-sample-next-app.yml
    - envsubst < k8s/ingress-prod.yml > k8s/ingress-prod-sample-next-app.yml
    - envsubst < k8s/certificate.yml > k8s/certificate-sample-next-app.yml
  script:
    - kubectl apply -f k8s/deployment-sample-next-app.yml
    - kubectl apply -f k8s/service-sample-next-app.yml
    - kubectl apply -f k8s/ingress-prod-sample-next-app.yml
    - kubectl apply -f k8s/certificate-sample-next-app.yml
  allow_failure: false
