name: ðŸ‡«ðŸ‡·

on: 
  - push
  - delete

jobs:
  mirror_gitlab:
    name: ðŸªž Gitlab
    runs-on: ubuntu-latest
    steps:
    - uses: SocialGouv/actions/mirror-gitlab@master
      with:
        project: SocialGouv/sre/test-sync
        token: ${{ secrets.SOCIALGROOVYBOT_GITLAB_TOKEN }}
