jobs:
  workflows-src-to-workflows:
    name: Convert
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        with:
          branch: "${{ steps.comment.outputs.branch }}"
          token: "${{ secrets.SOCIALGROOVYBOT_BOTO_PAT }}"
      - uses: "dhall-lang/setup-dhall@35fa9f606036a9b7138bcbc4d519021fdda7bd5e"
        with:
          version: "1.38.1"
      - name: Github Actions Dhall To Yaml
        run: |
          find .github/workflows-src -name '*.dhall' -type f -print0 |
            sort -buz |
            xargs -0 -i sh -xc '
              dhall lint --inplace {} --check &&
              dhall-to-yaml --file {} --output .github/workflows/$(basename {} .dhall).yaml
            '
      - env:
          GITHUB_TOKEN: "${{ secrets.SOCIALGROOVYBOT_BOTO_PAT }}"
        name: Commit changes
        uses: "EndBug/add-and-commit@a3adef035a1381dcf888c90b847240e2ddb9e008"
        with:
          add: ".github/workflows/"
          author_email: "${{ secrets.SOCIALGROOVYBOT_EMAIL }}"
          author_name: "${{ secrets.SOCIALGROOVYBOT_NAME }}"
          branch: "${{ steps.comment.outputs.branch }}"
          message: "chore(:robot:): workflows-src to workflows"
name: Github Actions Dhall
on:
  push:
    branches:
      - master
      - main
    paths:
      - ".github/workflows/workflows-src.yml"
